### ISSUE TITLE
Error during compiling

### ISSUE THREAD

**Issue by QPOZP** [DreymaR/BigBagKbdTrixPKL#12]
Error apears with and without admin rights.

![Screenshot_2](https://user-images.githubusercontent.com/62795321/98705280-740bac80-2375-11eb-8cf2-ca5a0416bfca.png)

**Comment by DreymaR** [comment]
I know, bad commit the last time. Please try the latest commit, that should fix it!

**Comment by QPOZP** [comment]
Alright, it's fixed now, thanks.
