### ISSUE TITLE
Ctrl + Shift + 9 in Slack doesn't turn on Quoting any more

### ISSUE THREAD

**Issue by felipe1982** [DreymaR/BigBagKbdTrixPKL#17]
I come from using the older pkl for about 5 years, and just yesterday upgraded to epkl. When using slack, I used to be able to type Ctrl + Shift + 9 to start a blockquote. This doesn't work with epkl

----

OS: windows 10
keyboard: US standard QWERTY
language: US standard
Geography: Australia

**Comment by DreymaR** [comment]
Look in your `EPKL_Settings_Default.ini` file and comment out or change the Hotkey using `^+9`. Then you should have yours back in action!

**Comment by felipe1982** [comment]
Thanks. Resolved
