### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by qwitwa** [DreymaR/BigBagKbdTrixPKL#2]
![image](https://user-images.githubusercontent.com/2302478/43032088-9931e10e-8ca6-11e8-919a-ee225d5a9952.png)

**Comment by DreymaR** [comment]
Ummm... did you set the language in PKL_Settings.ini to a language that isn't in the Languages folder?

I haven't added a UK English language file; feel free to send me one if you make it.

**Comment by DreymaR** [comment]
Okay, the isuse is fixed. Turns out I had made a more aggressive try-catch check for .ini file reads where PKL earlier just trudged on when it didn't find a file. In this case, the check proved too aggressive.

**Comment by qwitwa** [comment]
Thanks for this, looks like things are working now. ModDH is a great layout, so it's nice to have it working on my uni computers.  

Keep up the great work.
