### ISSUE TITLE
create help images not working? empty folder 

### ISSUE THREAD

**Issue by damElo850** [DreymaR/BigBagKbdTrixPKL#23]
hello,
I previously had v1.5 and changed to 2 but it doesn't seem to work properly 'generate state images' as it only creates empty directories. I changed the folder in the application settings

**Comment by DreymaR** [comment]
Hmmm. I just tested it and state images were made just fine for me.

Is your Inkscape version compliant with the EPKL HelpImageGenerator? It should be at least v1.0.

**Comment by damElo850** [comment]
that's right . after update working correctly
