### ISSUE TITLE
Rulemak is outdated

### ISSUE THREAD

**Issue by GeneralFailer** [DreymaR/BigBagKbdTrixPKL#3]
The included Rulemak layout version seems to have been outdated [since 2009](https://forum.colemak.com/post/5316/#p5316).

**Comment by DreymaR** [comment]
I see. But what is considered Rulemak now? Because I still adhere to the version with Latin letters on AltGr, since the others got rather messy. And there's also the issue of Bulmak.

I'll check whether my included version is consistent with the XKB one at least. Good call!

**Comment by DreymaR** [comment]
Okay, in the latest version I've updated Rulemak and added Bulmak, both with help images. I used the 2016 version since I personally feel that having latin letters on AltGr can be useful after all. We'll see whether there's a demand for the more "hard core" version with more kyrillic letters in it.
