### ISSUE TITLE
Cmk-eD-BeCaFr - First row does not work properly with an azerty keyboard

### ISSUE THREAD

**Issue by bistace** [DreymaR/BigBagKbdTrixPKL#37]
Hello,
I am trying to learn the `Cmk-eD-BeCaFr` layout but the first row does not print the correct characters when in an unshifted state. Indeed, instead of numbers, here is what it prints for numbers 1 to 0 (left is expected and right is the one actually printed):
```
1 = &
2 = é 
3 = "
4 = '
5 = (
6 = -
= = =
7 = è
8 = _
9 = ç
0 = à
```
I guess that this is because keycodes in the .ini file are not correct for an azerty keyboard. Could you please help me out?

**Comment by DreymaR** [comment]
Ah, you need to make sure you don't have VK mappings in your BaseLayout (they look like `##` entries).

Find the line `baseLayout      = Colemak\BaseLayout_Cmk-eD` in your layout.ini, and change the BaseLayout to `BaseLayout_Cmk-eD_VK-None`. This will make your mappings work, but unfortunately the number keys will no longer work with Win key shortcuts. You can't have both it seems.
