### ISSUE TITLE
Keys get stuck in WSL

### ISSUE THREAD

**Issue by drone-ah** [DreymaR/BigBagKbdTrixPKL#55]
Hi, and thanks for a great tool. It works fantastically. The main qualm I am having with it is the key getting stuck, but only in WSL. It seems to be fine in other apps 🙂 

My settings screen -> 
![image](https://user-images.githubusercontent.com/2621325/205434395-7f05fcde-91e7-4aa2-9929-46c302db0fab.png)

In WSL, it usually annoys me when I'm trying to delete part of a long line in the terminal (`terminator`) and it ends up deleting the whole line 🙁 

I've also tried it with other GUI applications like `gedit`.

I am currently using `wslg` as the xserver, but I also had the same issue with `GWSL`.

Is there any easy way for me to fix this?

Thanks Again,

**Comment by DreymaR** [comment]
I've had trouble with WSL vs AHK, I ended up just auto-suspending EPKL whenever WSL is active:
```
suspendingApps  = X bash.exe
``` 
This setting will do that.

That said, I just tested it with the latest EPKL commit and it seems to be fixed? Have you tried one of the very latest commits? There have been several fixes for old problems in them. I'll likely make a new release soon.
