### ISSUE TITLE
Remove warning msgs

### ISSUE THREAD

**Issue by mrx23dot** [DreymaR/BigBagKbdTrixPKL#58]
If I press "submit layout choice" I don't need to be asked:

- are you planning to write your changes to disk - yes because i didn't choose Cancel/exit
- disk write was successful - i wouldn't expect anything else in 2023, it's not 1950

**Comment by DreymaR** [comment]
You have misread the messages.
• The first message asks you whether you know what you're doing before writing to a file. This is common practice.
• The second message tells you that it worked, and asks you whether you want to restart EPKL right away.

Sometimes I don't want to restart immediately as I want to make more changes. Sometimes the write didn't go as planned so it's nice to know it did. Yes, in 2023. I doubt they had any file write dialogs in 1950, heh.
