### ISSUE TITLE
McAfee detects trojan Artemis!E16CE83C5E8B

### ISSUE THREAD

**Issue by Knochi** [DreymaR/BigBagKbdTrixPKL#61]
Wanted to use on corporate machine and EKPL.exe was deleted.

**Comment by Knochi** [comment]
Ah ok, guess IT department will not help with this. So I guess i have to get a custom keyboard ;-)

**Comment by DreymaR** [comment]
I know, they're not always helpful. At my work computer, I use Hasu's QUICKIE device to get Colemak-CAWS with Extend.
