### ISSUE TITLE
KeyHistory should be disabled by default

### ISSUE THREAD

**Issue by dfrvfmst** [DreymaR/BigBagKbdTrixPKL#63]
Currently EPKL silently records all the inputs in plain text with the [KeyHistory](https://www.autohotkey.com/docs/v1/lib/KeyHistory.htm) by default, which is not good from a security point of view. KeyHistory should be strictly a debugging tool.

Hiding the KeyHistory menu (with `advancedMode = no`) or disabling the KeyHistory shortcut (with `epklDebugHotkey = `) doesn't really stop EPKL from recording it. The user just have no way to access it interactively, while the recorded data still sits in memory.

Consider adding `#KeyHistory 0` by default, with a user overridable option to reenable it on demand.

**Comment by DreymaR** [comment]
I don't think that users running a keyboard program themselves on their own computer consider the AutoHotkey default KeyHistory a big security risk.

It's very easy for any concerned users to add the directive you mention and compile. You are the first. I believe that the majority of users would rather, like me, have the KeyHistory available for debugging – which surprisingly often becomes useful when setting up advanced options.

**Comment by dfrvfmst** [comment]
Thanks for you replying.

I'm not very familiar with AutoHotKey 1. Is the `#KeyHistory` impossible to be overridden in runtime once it's compiled? Because as a debugging tool, it should only be enabled when needed, and it's what most other software do.

Say if you want to tweak layouts, but how many time would you actually tweak it? It should be tweaked once and forget it (Do you change Group Policy all the time?). So I would image most users messing around the program for the first week and then being done with it for years. KeyHistory at this point will serve no use, except adding security risk. Even if you ignore the security risk, continuously logging (as plain text) in the background also adds more CPU usage that are mostly wasted, and EPKL is a latency-oriented program running under realtime priority, so any CPU cycle should matter.

---

If AutoHotKey doesn't really allow `#KeyHistory` to be overridden in runtime (So you can't make it user-overridable in config):

Does AutoHotKey allow executing external programs? If you compile a "standalone KeyHistory" program which the sole purpose is to log inputs, and then add a entry to start that KeyHistory program in the main program, it would:

- Allow users to start debugging key presses anytime they want
- Keep the KeyHistory disabled by default when users are not actively debugging it

**Comment by DreymaR** [comment]
No, to change the `#KeyHistory` directive you have to recompile. That's how compiler directives work, I'm afraid. At least ttbomk.

I don't know what this "most other software" is. I don't know of other keyboard programs like (E)PKL for Windows, come to think of it. As for "most other software" in the AHK universe, I think you're wrong: Many scripts just leave it on and never worry about it. As I said above, you're the first I've heard of.

**Comment by DreymaR** [comment]
I may indeed add this piece of information to the README. Just, I don't think most users read it through. There's already a lot of info to take in there.

If you can make such a standalone program work, then please make a PR for it! It'd be a useful thing. However: I have my doubts that tack will work. The main program needs to have the keyboard hook to make the hotkeys that remap keys etc, and the hook is what KeyHistory uses. Having a separate hook in the standalone program will likely lead to disaster as you'll incur "hook competition" and both scripts may become unreliable. Maybe if you make sure the standalone gets priority and has zealous pass-through... but I won't bet on it at this point.

**Comment by dfrvfmst** [comment]
Doing some very basic researches I believe that `#KeyHistory` is a compile time parameter and it's hard-coded into the resulting binary. There is no way to override it in runtime.

The very first thing I came into mind is creating two different entrypoint programs with different KeyHistory parameter.

This would be:

```
;;EPKL.ahk
#KeyHistory 0
#Include %A_ScriptDir%\EPKL_Source
...
```

```
;;EPKL_debug.ahk
#KeyHistory 500
#Include %A_ScriptDir%\EPKL_Source
...
```

Then make changes to the `_PKL_main.ahk` to add an entry "Restart in debug mode" (taking over `advancedMode`)

Pros:

- `KeyHistory` is handled by EPKL directly. No race condition

Cons:

- AutoHotKey doesn't seem to have the concept of dynamic-linking. So compiling two entrypoint programs results in two fat and largely redundant programs being created instead of reusing the codes (Not very large, only 1MiB larger, but indeed wasted storage space).

---

The next thing I thought of is [KeyboardStateView](https://www.nirsoft.net/utils/keyboard_state_view.html). Experiment shows that EPKL always takes the higher priority over KeyboardStateView, no matter the starting order. KeyboardStateView license allows redistributing the program as long as no changes are made to its program.

The plan would be to:

1. Distribute KeyboardStateView with EPKL
2. `#KeyHistory 0`
3. Make changes to `_PKL_main.ahk` so the calling to `keyHistory` would instead open this external program
4. Optionally show a info message box that KeyboardStateView only displays the remapped input

Pros:

- Smaller than compiling two different programs

 Cons:

- KeyboardStateView only shows the remapped key input, not the original input. In order to find out the original Virtual Key hex the user would have to disable EPKL temporarily (`Ctrl + Shift + 3`, so not very hard)

---

Either would be trivial to implement with minimal changes to the project. Which do you think would be easier on casual users?

**Comment by DreymaR** [comment]
Neither tack looks practical to me. Most users don't want that kind of complexity for a concern that most users don't even care about. And god knows setting up EPKL is already too complex for a lot of new users!

**Comment by dfrvfmst** [comment]
You still missed my point. The point is:

> I would image most users messing around the program for the first week and then being done with it for years

From your PoV KeyHistory is frequently used by your users. This happens only because those who contacted you were often having issues with EPKL and those who didn't have an issue have no reason to contact you, also known as survivorship bias. If you ask each users you've supported in one year whether they still actively utilize KeyHistory even after their issues were fixed, the answer would probably be a boldly no.

But it's OK. At least now that you've addressed the issue in README so it's now up to the users to decide whether to keep the KeyHistory on (they don't read manual you say? ~then tell them to RTFM~).
