### ISSUE TITLE
Anyway to auto-disable on certain windows? Most games really hate EPKL and won't work with it enabled.

### ISSUE THREAD

**Issue by wadbr** [DreymaR/BigBagKbdTrixPKL#8]
is there a way to add exe names to a list which will make epkl auto disable itself when it detects the focus is on that window? And preferably re-enable itself otherwise. 

Most video games will refuse any keyboard entry when epkl is enabled, or will behave really weirdly.

This will work really well with alt-tabbing from games or other apps that don't like epkl.

**Comment by DreymaR** [comment]
At the moment, no. You have to press the Suspend hotkey (default Ctrl+Shift+`) when entering and leaving the window.

It's a neat idea. Maybe some day...

**Comment by DreymaR** [comment]
EPKL now has a SuspendingApps setting that lets you specify program windows that automatically suspend EPKL. See the Settings file. Yay!

**Comment by Vosheck** [comment]
Any way we could have the suspension occur only when the application window is focused, instead of running? I alt tab a lot during the down time in online video games.
