### ISSUE TITLE
Doesn't work with PowerToys' Quick Accent

### ISSUE THREAD

**Issue by Ryuo1** [DreymaR/BigBagKbdTrixPKL#84]
EPKL ON:
![eOwmADMMyp](https://github.com/DreymaR/BigBagKbdTrixPKL/assets/77712873/41d46d07-44ea-4d8f-8df8-78f8bfba3925)

EPKL OFF:
![cGUFw9j99c](https://github.com/DreymaR/BigBagKbdTrixPKL/assets/77712873/5645a020-9a47-40f2-94e8-3d6560f5757a)

**Comment by DreymaR** [comment]
I don't know why so many are commenting on EPKL vs PowerToys these days. Maybe PowerToys is becoming more popular?

The EPKL Readme explains why this happens: Hook competition. Unfortunately, that's an OS issue and there isn't a lot to be done about it to my knowledge.

I've updated the Readme to explain this even more clearly.
https://github.com/DreymaR/BigBagKbdTrixPKL?tab=readme-ov-file#known-issues
