### ISSUE TITLE
EPKL has an issue with ShareX

### ISSUE THREAD

**Issue by Ryuo1** [DreymaR/BigBagKbdTrixPKL#85]
The Colemak layout has an issue with ShareX that it doest't register the key 'PrtSc' (printscreen) when on the Colemak layout, however it works fine on the QWERTY layout.

**Comment by DreymaR** [comment]
The phenomenon/problem of Keyboard Hook competition is described in the README. Did you read it?

What you can try is to unset EPKL's hotkey for the PrtScn key. It should be in the EPKL_Layouts file. You can uncomment it there, or give it an `--` entry in an Override file.

**Comment by DreymaR** [comment]
That's just it, if you re-remap it to PrtScn (uncomment the qwPSC mapping in EPKL_Layouts_Default) I don't think that'll make your other program any happier as they'll still be competing for the same hook.

Did you do as I said and read up about hook competition? Then you understand what we're up against here.

If there were any key combo you need from your gesture, it'd be possible to just map it to something else in EPKL. But that's not the case here?

**Comment by Ryuo1** [comment]
respectfully i did not understand when i read that 😭 (hook competition)
what if i just use the windows keyboard layout of colemak and keep EPKL only for extend?

**Comment by DreymaR** [comment]
If you use several programs that utilize low-level keyboard hooks at the same time, they will compete for priority.

This means you probably can't use ShareX and EPKL at the same time without problems. I'm not sure, but it is a possibility.

I use the Windows Snipping Tool for screenshots; I even have an EPKL shortcut or two for it. So I haven't tried ShareX.
