### ISSUE TITLE
Caps lock setting not applied

### ISSUE THREAD

**Issue by JapanYoshi** [DreymaR/BigBagKbdTrixPKL#88]
I’m trying to use EPKL to type in Dvorak with Google Japanese Input—It doesn’t let me change the keyboard layout without a registry hack, and I’d rather not change the registry on a company PC.

The first problem is that the ` key is not recognized as the hankaku/zenkaku key on a Japanese computer keyboard. It’s used to toggle the IME on and off, so it not working is a bit of an issue.

But no problem, I can turn it on with Hiragana/Katakana (passed through by EPKL, so it works) and turn it off with Caps Lock.

However, no matter how many times I tell the EPKL settings menu to use Caps Lock as Caps Lock (which it calls “waste”), it refuses to respect my settings, instead activating a command pad that I will not need on a full-size keyboard.

I just want to type Dvorak, man, why is it so hard for me?!

Anyway, please advise on how to disable the Caps Lock command menu, thanks!

**Comment by DreymaR** [comment]
Okay, hopefully good news on this topic: In the latest EPKL commit, there is a new mapping that allows you to leave a key alone. This is its syntax for the CapsLock key, and to work it'll have to be placed so it overrides the default (typically in an _Override file):
`QWCLK = Unmapped`

In the Special Keys GUI, as well as the KeyMapper, this syntax has been added. Setting the Special Key to CapsLock as you tried before should now use the `Unmapped` syntax which leaves the key completely alone.
