### ISSUE TITLE
How can I change level3/4 key? 

### ISSUE THREAD

**Issue by eclipseo** [DreymaR/BigBagKbdTrixPKL#89]
Hello, 

I've searched but I didn't find out: how can I change the key that allow to type level 3 characters? I'd like to use RCtrl or CapsLock but I don't get how I can switch, either in the gui, or in the ini files.

Thanks.

**Comment by DreymaR** [comment]
You mean the AltGr key. Yeah, I've not had success trying to let EPKL move that key around. Windows has a somewhat strange way of using it.

Therefore, to move my AltGr key I use SharpKeys (registry remapping). It's included, in the Other folder.
